### ISSUE TITLE
missing link: what are serverless functions

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/azure-dev-docs.de-de#2]
Using the documentation the tree on the left starts with the topic "deploy serverless functions", and the first content is 3 levels deeper "1 Configure your environment"

But the first topic should also explain what a "serverless function" is. It would be much more helpful if I could first read an introduction what is this mystic "serverless function" before to start a deep dive how to deploy. I recommend a link where the user can read what is a serverless function. Currently I need to use a search engine to find out.

And even then it is not yet clear what would be the best starting point to read. 
https://azure.microsoft.com/de-de/services/functions/
https://docs.microsoft.com/de-de/azure/azure-functions/
https://docs.microsoft.com/de-de/azure/azure-functions/functions-overview

The goal of the "Azure for Python" should be to explain to a python developer how he should or could use Azure, whithout the extra need of search engienes. So please make this process a little bit easier by providing some links to deeper explaining where this is useful.

The same issue with web apps, containers, ...

What I miss is an easy to find overview comparing serverless functions, web apps, containers...
I can read how to use and how to deploy them, but I don't get an idea which of them is the best for my goal anh how they differ.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 1622f2c8-9622-97e8-e1c6-b086ac690056
* Version Independent ID: ba3c2809-8f22-42ac-b692-9dcc2e7c49f9
* Content: [Tutorial: Erstellen und Bereitstellen einer serverlosen Azure Functions-Instanz in Python mit Visual Studio Code](https://docs.microsoft.com/de-de/azure/developer/python/tutorial-vs-code-serverless-python-01)
* Content Source: [articles/python/tutorial-vs-code-serverless-python-01.md](https://github.com/MicrosoftDocs/azure-dev-docs.de-DE/blob/live/articles/python/tutorial-vs-code-serverless-python-01.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
The details you want are on https://docs.microsoft.com/en-us/azure/guides/developer/azure-developer-guide. I do need to add a link to https://docs.microsoft.com/en-us/azure/developer/python/cloud-development-overview to that developer guide, which should help. But otherwise, we are assuming that the reader already knows common industry terms like serverless and containers.

**Comment by aisbergde** [comment]
You see, there are some stupid database developers and BI experts like me, which never tried to program an app and because of this started to read the documentation at some point in the tree and not findig the content related to the point in the tree.
 
But my point was not so much about the missing description but more about the general effect, that the documentation is starting 3 levels deeper than the main topic. It started with "serverless functions" but this is just one example about the very strange documentation which starts on a very deep detail level missing descriptions on a higher level. This is a general issue of the documentation which makes the documentation hard to read if the first entry is not explaining higher levels.

I try a different example. if this is the tree

- 2019
- 2020
  - 2020-01
    - 2020-01-01
    - 2020-01-02

I am interested in "2020", but what I get is "2020-01-01" and now I should read all the hundreds topics of the year to understand what is "2020".

And a solution would be:
- 2019
- 2020
  - 2020-01
    - About 2020
    - 2020-01-01
    - 2020-01-02

or a better solution would be to have also a documentation page for "2020" and for "2020-01".

Have a look on the standard way creating wikis in Azure DevOps. I can omit content for parent topics, but the normal way when creating new pages in the Wiki is, that for each topic on each level a page is created.

**Comment by kraigb** [comment]
Thanks. I understand your concerns, which arise from various experiments on the TOC that attempt to satisfy conflicting feedback from multiple sources. Unfortunately, we've not found any one TOC structure that happens to satisfy everyone. We get complaints when the TOC is shallow, or when it's organized around a different model, or .... There are efforts underway within the docs organization as a whole to do away, in fact, with TOC structures like this altogether, using a model of "collections" that would allow the same content to be organized into multiple groups in different places.

We also struggle with a somewhat stylistic quandry over whether each node in the TOC should have some kind of associated article. In this case, should we have a distinct overview article under the top-level serverless node in the TOC to explain what we mean by "serverless"? Offhand, that article wouldn't be very long, and though it'd be nice to have that article compare other compute options on Azure, we'd then need to repeat that content under Container and Web Apps, which doesn't end up working very well.

Part of the difficulty is also that TOC node with children cannot have content of their own, which is where this kind of thing would naturally fit. Compounding the problem, too, is that simple overview pages end up being a lot of trouble to maintain (and therefore get out of sync with the rest of the content), and then tend to "perform" poorly in terms of page view and visitors, and therefore end up getting earmarked for retirement to simply reduce the overall number of articles we have to maintain as a whole organization.

We're also trying to find better ways to organize different variants of similar content, e.g. portal vs. CLI vs. VS Code variants. The options we have today are not optimal and have a variety of problems, so we try to make the best out of what we have within the time we really have to commit to such matters in the context of all other priorities.

And like I said, we're working on the assumption that visitors to the dev center already understand certain common terms like serverless and containers. Ideally we'd have an easy way to surface useful definitions inline without cluttering the content, which is a feature that our site platform team is considering but, alas, it not available at the present.

So again, I understand where you're coming from, but within the current TOC model that we're working with and other constraints on how we are able to publish and manage content, I won't be making any changes to the TOC at this time based on your comments. My apologies that it's not an optimal structure for you, but like I said, it's impossible to satisfy everyone simultaneously. In any case, I'll retain your comments as further input whenever we have another (inevitable) round of discussion around TOC structure.

**Comment by aisbergde** [comment]
I am impressed about your answer. In short, you know the issues even much better than I. And of course a general approach is required. It looks like you (the documentation team) are really hard working regarding this questions.

Now I even don't know should I progress to deliver feedback. 

My vision is a documentation which is some kind of consistent by it selfs where I don't need to use search engines but where the required links are already there. I hope you will find this compromise. In General the documentation is really good and the first point for me to search - and find.

**Comment by kraigb** [comment]
Oh, feedback is always valuable and appreciated! But please offer it without attachment or expectation because, as you can see, there are often many considerations that go into whether we can follow that feedback or make the suggested changes. And oftentimes, too, such feedback adds backing to more systemic changes or platform improvements that would solve a similar class of problems across the board rather than making many small edits in isolated locations.

We do try to provide helpful links in many places, but as you can expect, we have to draw a line somewhere by making certain assumptions. In some cases we also try to avoid links that would potentially distract the reader and taken them off to some other piece of content that isn't exactly relevant to their primary purpose. Always a delicate balance!

In any case, thanks for the thoughtful conversation.

**Comment by kraigb** [comment]
#close

Please close this issue as the primary request was resolved a month ago.
